# Generated by Django 5.1.7 on 2025-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Project URL')),
            ],
        ),
    ]
