# Generated by Django 5.1.7 on 2025-09-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azinapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Job'),
        ),
    ]
