# Generated by Django 5.1.7 on 2025-09-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azinapp', '0005_alter_contact_options_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
