# Generated by Django 5.1.7 on 2026-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azinapp', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('product', 'Product Photography'), ('corporate', 'Corporate Events'), ('portrait', 'Portrait'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='media_gallery/', verbose_name='Image or Video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_gallery/thumbnails/', verbose_name='Thumbnail')),
                ('is_video', models.BooleanField(default=False, verbose_name='Is Video')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
