# Generated by Django 5.1.7 on 2026-08-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azinapp', '0009_databaseproject_decoreproject_graphicdesignproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelservice',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='travelserviceimage',
            name='service',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='TravelService',
        ),
        migrations.DeleteModel(
            name='TravelServiceImage',
        ),
    ]
