# Generated by Django 5.1.7 on 2026-08-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azinapp', '0010_remove_travelservice_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='price',
        ),
    ]
